package MModel;

public class CONF {

public static String MEX = "0"; //Mex status
public static String DEMO = "0"; //Demoversion
public static String SWTBNR = "+46812200749"; //Switchboard number
public static String LA = "0"; //Line access
public static String DBG = "1"; //Debug status
public static String CCODE = "46"; //Country code
public static String HGP = "197"; //Hangup key in Hex
public static String CLIENT = "mobisma ME"; //J2Me Client name
public static String JAD = "C:\\Mobisma\\panasonicme.jad"; //Jad name
public static String DTMF1 = "p&LA#"; //Dtmf mask
public static int IS = 4; //Internal call length
public static String IMEI = "GEDIEBJHHCIIECHJI"; //Imei number decoded
public static String VM = "222"; //Operator Voicemailnumber
public static String PBXVM = "500"; //Switchboards voicemail
public static String ANKN = "201"; //Extension
public static String PRGNAME = "MobismaME"; //Midlet name
public static String PCODE = ""; //Pin code
public static String LANG = "1"; //Language number
public static String IMEI2 = "35615802271157201"; //IMEI okrypterad
public static String DTMFP = ","; //DTMF-tecken för paus
public static String PRECODE = "*7"; //Pre edit code
public static String COMPANYNAME = "Jens företag"; //Company name of registrated owner
public static String NAME = "åäöÅÄÖ"; //Name of registrated owner
public static String PBXID = "15"; //Id number of Pbx name
public static String DL = "0"; //Default lang 1 = inte engelska, 0 = engelska
public static String PBRAND = "HTC"; //Phone brand
public static String PMODEL = "TouchDiamond"; //Phone model
public static String PBXNAME = "Panasonic TDE/NCP"; //Brandname of PBX
public static String IMEIPROPERTY = "1"; //Api used for retrieving IMEI number
public static String GSMNUMBER = "+46720018019"; //Number of possible GSM Modem
public static String TESTURL = "http://www.mobisma.com/socketapi/mobismaSRV.php"; //Server url for debug
public static String INTURL = "socket://127.0.0.1:8100"; //Server url for internal communcation
public static String EXTURL = "http://www.mobisma.com:80/socketapi/mobilesock.php"; //Server url for sending logdata
public static int AUTOS = 1; //Om applikationen ska autostarta
public static int AUTOSM = 1; //Om applikationen ska autostarta minimerad
public static int FMINIMIZE = 0; //Om minimieringen ska vara vara total
public static String KONFRUMSNR = "0"; //Konferens rumsnummer
public static String ACCESSVM = ""; //Access kod till Voicemail
public static String ACCESSKONF = "0"; //Access kodr till Konferens
public static String DTMFPDUR = "500"; //Pause i millisekunder mellan dtmftoner
public static String HANGUPPAUSE = "2000"; //Pause i milliskeunder vid omdirigering av samtal
public static String CPREFIX = "0"; //Countryprefix när man ringer med landskod i sitt eget land
public static String PBXPREFIX = "PBX"; //Text som syns före nummret när man ringer via växeln
public static String DEBUG = "1"; //Debugläge för test lokalt Mobisma
public static String DEMO_EXPIRES_MS = "1295531673345"; //When DEMO version expires expressed in Java System.currentTimeMilliseconds().
public static int HANGUPTYPE = 1; //If New called will be dialed directly or when old call is disconnected
public static String PCODEMASK = "*47&ANKN;&PCODE;"; //How the pincode should be formatted
public static String PGTYPE = "1"; //Wich programtype ME or SC
public static String EXT1 = "201"; //Saved Extensionlist
public static String EXT2 = "202"; //Saved Extensionlist
public static String EXT3 = "203"; //Saved Extensionlist
public static String EXT4 = "204"; //Saved Extensionlist
public static String EXT5 = "205"; //Saved Extensionlist
public static String EXT6 = "206"; //Saved Extensionlist
public static String EXT7 = "207"; //Saved Extensionlist
public static String EXT8 = "208"; //Saved Extensionlist
public static String WWW = "http://www.mobisma.com"; //URL To Mobisma
public static String APIVER = "4_5"; //Version of API/JDK
public static int NOTIFICATIONS = 1; //Android specific if Notifications should be sjown
public static String MAKESERVER = "84.246.134.72"; //Länk till makeservern
public static String IDDCODE = "00"; //International direct dialing code
public static String AREACODEREMOVE = "0"; //Number to remove on areacode when dialing abroad
public static String EMERGENCYNUMBERS = "#112#11414#"; //Emergencynumbers
public static String PROGVERSION = "2.1.7"; //Programvaru version
public static int ENCRYPTEDXML = 0; //If the xmlfiles are encrypted
public static int IHPORT = 80; //Wich Port to use for CT-IP communication
public static String IHURL = "http://make.mobisma.com/MobismaCTBridge/Service1.asmx/CTExchange"; //Wich URL adress to use for CT-IP communication
public static int MINIMISE = 1; //Should the minimise be done by client or server
public static int NATIVE = 3; //Wich native version
public static String xhvtype = "MOBCTEX"; //
public static String BBCONDATA = "1"; //Blackberry connection data
public static String JAVAVERSION = "2.x.x"; //Java version from version.txt
public static String SERVERVERSION = "2.1.7"; //Server version
public static String DTMFSENDTYPE = "2"; //Wich sendtype for dtmf to be used
public static String PRINT_DB_debug = "1"; //System debug out on eller off
public static String CTDTMFPREFIX = "*23*"; //Prefix for CT system when using DTMF
public static String ICONDIR = "/prg_icon/"; //Where the icons are put in the J2ME project
public static String CTSYSTEM = "MOBCTEX"; //CT-System if used
public static String CTDIALING = "*cmd:d#*stat:1#*ankn:%ANKN;"; //Parameters to send to CT System when dialing
public static String CTHANGUP = "*cmd:d#*stat:0#*ankn:%ANKN;"; //Parameters to send to CT System when hangingup
public static String CTDIALTEXT = "text"; //Text parameter name for sending CT Dialing Busystatus
public static String JDEMO = "1"; //Check av Demoperiod
public static String CTEPOST = "peter.albertsson@mobisma.com"; //Id for Exchangeserver
public static String[] initdatabasedata = new String[150];

public CONF() {
initdatabasedata[0] = "0"; //Ingen parameter
initdatabasedata[1] = ""; //Inte definierad i m_confvars
initdatabasedata[2] = ""; //Inte definierad i m_confvars
initdatabasedata[3] = ""; //Inte definierad i m_confvars
initdatabasedata[4] = "0"; //Line access
initdatabasedata[5] = "+46812200749"; //Switchboard number
initdatabasedata[6] = ""; //Inte definierad i m_confvars
initdatabasedata[7] = ""; //Inte definierad i m_confvars
initdatabasedata[8] = ""; //Inte definierad i m_confvars
initdatabasedata[9] = "201"; //Extension
initdatabasedata[10] = ""; //Pin code
initdatabasedata[11] = ""; //Inte definierad i m_confvars
initdatabasedata[12] = "222"; //Operator Voicemailnumber
initdatabasedata[13] = "1"; //Debug status
initdatabasedata[14] = ""; //Inte definierad i m_confvars
initdatabasedata[15] = "46"; //Country code
initdatabasedata[16] = "0"; //Mex status
initdatabasedata[17] = ""; //Inte definierad i m_confvars
initdatabasedata[18] = "500"; //Switchboards voicemail
initdatabasedata[19] = "1"; //Language number
initdatabasedata[20] = "0"; //Demoversion
initdatabasedata[21] = ""; //Inte definierad i m_confvars
initdatabasedata[22] = "Jens företag"; //Company name of registrated owner
initdatabasedata[23] = "åäöÅÄÖ"; //Name of registrated owner
initdatabasedata[24] = ""; //Inte definierad i m_confvars
initdatabasedata[25] = ""; //Inte definierad i m_confvars
initdatabasedata[26] = ""; //Inte definierad i m_confvars
initdatabasedata[27] = "*7"; //Pre edit code
initdatabasedata[28] = ""; //Inte definierad i m_confvars
initdatabasedata[29] = ""; //Inte definierad i m_confvars
initdatabasedata[30] = ""; //Inte definierad i m_confvars
initdatabasedata[31] = ""; //Inte definierad i m_confvars
initdatabasedata[32] = ""; //Inte definierad i m_confvars
initdatabasedata[33] = ""; //Inte definierad i m_confvars
initdatabasedata[34] = ""; //Inte definierad i m_confvars
initdatabasedata[35] = "15"; //Id number of Pbx name
initdatabasedata[36] = "MobismaME"; //Midlet name
initdatabasedata[37] = ""; //Inte definierad i m_confvars
initdatabasedata[38] = ""; //Inte definierad i m_confvars
initdatabasedata[39] = "GEDIEBJHHCIIECHJI"; //Imei number decoded
initdatabasedata[40] = ""; //Inte definierad i m_confvars
initdatabasedata[41] = ""; //Inte definierad i m_confvars
initdatabasedata[42] = ""; //Inte definierad i m_confvars
initdatabasedata[43] = "1"; //Default lang 1 = inte engelska, 0 = engelska
initdatabasedata[44] = ""; //Inte definierad i m_confvars
initdatabasedata[45] = "HTC"; //Phone brand
initdatabasedata[46] = "TouchDiamond"; //Phone model
initdatabasedata[47] = ""; //Inte definierad i m_confvars
initdatabasedata[48] = ""; //Inte definierad i m_confvars
initdatabasedata[49] = ""; //Inte definierad i m_confvars
initdatabasedata[50] = ""; //Inte definierad i m_confvars
initdatabasedata[51] = "201"; //Saved Extensionlist
initdatabasedata[52] = "202"; //Saved Extensionlist
initdatabasedata[53] = "203"; //Saved Extensionlist
initdatabasedata[54] = "204"; //Saved Extensionlist
initdatabasedata[55] = "205"; //Saved Extensionlist
initdatabasedata[56] = "206"; //Saved Extensionlist
initdatabasedata[57] = "207"; //Saved Extensionlist
initdatabasedata[58] = "208"; //Saved Extensionlist
initdatabasedata[59] = ""; //Inte definierad i m_confvars
initdatabasedata[60] = ""; //Inte definierad i m_confvars
initdatabasedata[61] = ""; //Inte definierad i m_confvars
initdatabasedata[62] = ""; //Inte definierad i m_confvars
initdatabasedata[63] = ""; //Inte definierad i m_confvars
initdatabasedata[64] = ""; //Inte definierad i m_confvars
initdatabasedata[65] = ""; //Inte definierad i m_confvars
initdatabasedata[66] = ""; //Inte definierad i m_confvars
initdatabasedata[67] = ""; //Inte definierad i m_confvars
initdatabasedata[68] = ""; //Inte definierad i m_confvars
initdatabasedata[69] = ""; //Inte definierad i m_confvars
initdatabasedata[70] = ""; //Inte definierad i m_confvars
initdatabasedata[71] = ""; //Inte definierad i m_confvars
initdatabasedata[72] = ""; //Inte definierad i m_confvars
initdatabasedata[73] = ""; //Inte definierad i m_confvars
initdatabasedata[74] = ""; //Inte definierad i m_confvars
initdatabasedata[75] = ""; //Inte definierad i m_confvars
initdatabasedata[76] = ""; //Inte definierad i m_confvars
initdatabasedata[77] = ""; //Inte definierad i m_confvars
initdatabasedata[78] = ""; //Inte definierad i m_confvars
initdatabasedata[79] = ""; //Inte definierad i m_confvars
initdatabasedata[80] = ""; //Inte definierad i m_confvars
initdatabasedata[81] = ""; //Inte definierad i m_confvars
initdatabasedata[82] = ""; //Inte definierad i m_confvars
initdatabasedata[83] = ""; //Inte definierad i m_confvars
initdatabasedata[84] = ""; //Inte definierad i m_confvars
initdatabasedata[85] = ""; //Inte definierad i m_confvars
initdatabasedata[86] = ""; //Inte definierad i m_confvars
initdatabasedata[87] = ""; //Inte definierad i m_confvars
initdatabasedata[88] = ""; //Inte definierad i m_confvars
initdatabasedata[89] = ""; //Inte definierad i m_confvars
initdatabasedata[90] = ""; //Inte definierad i m_confvars
initdatabasedata[91] = ""; //Inte definierad i m_confvars
initdatabasedata[92] = ""; //Inte definierad i m_confvars
initdatabasedata[93] = ""; //Inte definierad i m_confvars
initdatabasedata[94] = ""; //Inte definierad i m_confvars
initdatabasedata[95] = ""; //Inte definierad i m_confvars
initdatabasedata[96] = ""; //Inte definierad i m_confvars
initdatabasedata[97] = ""; //Inte definierad i m_confvars
initdatabasedata[98] = ""; //Inte definierad i m_confvars
initdatabasedata[99] = ""; //Inte definierad i m_confvars
initdatabasedata[100] = ""; //Inte definierad i m_confvars
initdatabasedata[101] = "+46720018019"; //Number of possible GSM Modem
initdatabasedata[102] = ""; //Inte definierad i m_confvars
initdatabasedata[103] = ""; //Access kod till Voicemail
initdatabasedata[104] = "0"; //Access kodr till Konferens
initdatabasedata[105] = ""; //Inte definierad i m_confvars
initdatabasedata[106] = ""; //Inte definierad i m_confvars
initdatabasedata[107] = ","; //DTMF-tecken för paus
initdatabasedata[108] = "00"; //International direct dialing code
initdatabasedata[109] = "0"; //Number to remove on areacode when dialing abroad
initdatabasedata[110] = "2.x.x"; //Java version from version.txt
initdatabasedata[111] = "2.1.7"; //Server version
initdatabasedata[112] = "2"; //Wich sendtype for dtmf to be used
initdatabasedata[113] = "1"; //If New called will be dialed directly or when old call is disconnected
initdatabasedata[114] = "80"; //Wich Port to use for CT-IP communication
initdatabasedata[115] = "http://make.mobisma.com/MobismaCTBridge/Service1.asmx/CTExchange"; //Wich URL adress to use for CT-IP communication
initdatabasedata[116] = "1"; //Check av Demoperiod
initdatabasedata[117] = "peter.albertsson@mobisma.com"; //Id for Exchangeserver
initdatabasedata[118] = ""; //Inte definierad i m_confvars
initdatabasedata[119] = ""; //Inte definierad i m_confvars
initdatabasedata[120] = ""; //Inte definierad i m_confvars
initdatabasedata[121] = ""; //Inte definierad i m_confvars
initdatabasedata[122] = ""; //Inte definierad i m_confvars
initdatabasedata[123] = ""; //Inte definierad i m_confvars
initdatabasedata[124] = ""; //Inte definierad i m_confvars
initdatabasedata[125] = ""; //Inte definierad i m_confvars
initdatabasedata[126] = ""; //Inte definierad i m_confvars
initdatabasedata[127] = ""; //Inte definierad i m_confvars
initdatabasedata[128] = ""; //Inte definierad i m_confvars
initdatabasedata[129] = ""; //Inte definierad i m_confvars
initdatabasedata[130] = ""; //Inte definierad i m_confvars
initdatabasedata[131] = ""; //Inte definierad i m_confvars
initdatabasedata[132] = ""; //Inte definierad i m_confvars
initdatabasedata[133] = ""; //Inte definierad i m_confvars
initdatabasedata[134] = ""; //Inte definierad i m_confvars
initdatabasedata[135] = ""; //Inte definierad i m_confvars
initdatabasedata[136] = ""; //Inte definierad i m_confvars
initdatabasedata[137] = ""; //Inte definierad i m_confvars
initdatabasedata[138] = ""; //Inte definierad i m_confvars
initdatabasedata[139] = ""; //Inte definierad i m_confvars
initdatabasedata[140] = ""; //Inte definierad i m_confvars
initdatabasedata[141] = ""; //Inte definierad i m_confvars
initdatabasedata[142] = ""; //Inte definierad i m_confvars
initdatabasedata[143] = ""; //Inte definierad i m_confvars
initdatabasedata[144] = ""; //Inte definierad i m_confvars
initdatabasedata[145] = ""; //Inte definierad i m_confvars
initdatabasedata[146] = ""; //Inte definierad i m_confvars
initdatabasedata[147] = ""; //Inte definierad i m_confvars
initdatabasedata[148] = ""; //Inte definierad i m_confvars
initdatabasedata[149] = ""; //Inte definierad i m_confvars
}
}
